use argon2::{
    Argon2, PasswordVerifier,
    password_hash::{PasswordHasher, SaltString},
};
use axum::{
    Router,
    extract::Json,
    routing::{get, post},
};
use dotenvy::dotenv;
use log::info;
use rand_core::OsRng;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::env;
use tower_http::trace::TraceLayer;

#[tokio::main]
async fn main() {
    // load environment variables from .env file
    // ref: https://github.com/allan2/dotenvy/blob/v0.15.7/README.md
    dotenv().expect(".env file not found");

    // initialize the logger
    // ref: https://github.com/tokio-rs/tracing/blob/tracing-subscriber-0.3.19/README.md
    tracing_subscriber::fmt::init();

    let app = Router::new()
        .route("/api", get(root))
        .route("/api/auth/signup", post(signup))
        // set up logging middleware
        // ref: https://docs.rs/axum/0.8.4/axum/struct.Router.html#example-3
        .layer(TraceLayer::new_for_http());

    let host = "0.0.0.0";
    let port = env::var("PORT").unwrap();
    // start the server
    // ref: https://docs.rs/axum/0.8.4/axum/index.html#example
    let listener = tokio::net::TcpListener::bind(format!("{}:{}", host, port))
        .await
        .unwrap();
    info!("Server running on http://{}:{}", host, port);
    axum::serve(listener, app).await.unwrap();
}

// root handler
// ref: https://docs.rs/axum/0.8.4/axum/handler/index.html
async fn root() -> Json<serde_json::Value> {
    Json(json!({ "status": "works" }))
}

// TODO: validation
#[derive(Serialize, Deserialize)]
struct Signup {
    email: String,
    name: String,
    password: String,
}

fn hash_password(password: &str) -> String {
    let params = argon2::ParamsBuilder::new()
        .m_cost(47104)
        .t_cost(2)
        .p_cost(1)
        .build()
        .unwrap();
    let argon2 = Argon2::new(argon2::Algorithm::Argon2id, argon2::Version::V0x13, params);
    let salt = SaltString::generate(&mut OsRng);

    argon2
        .hash_password(password.as_bytes(), &salt)
        .unwrap()
        .to_string()
}

fn verify_password(password: &str, password_hash: &str) -> bool {
    let parsed_hash = argon2::PasswordHash::new(password_hash).unwrap();
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed_hash)
        .is_ok()
}

// signup handler with json input
// ref: https://docs.rs/axum/0.8.4/axum/extract/index.html
async fn signup(Json(input): Json<Signup>) -> Json<serde_json::Value> {
    // TODO: impl
    Json(serde_json::to_value(input).unwrap())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    /// to ensure that we can verify existing password hashes generated by js
    /// server.
    fn verify_existing_hash() {
        let password = "jack@example.com";
        let old_hash = "$argon2id$v=19$m=47104,t=2,p=1$Wej+XgzGzI6kDYK+8F3DPA$9aeemDzDmYWBr3aUBiUl4m3WvcFUOB1f1+aSfnUM5X4";
        assert!(verify_password(password, old_hash));
    }

    #[test]
    /// to ensure that we can verify newly created password hashes
    fn verify_new_hash() {
        let password = "jack@example.com";
        let new_hash = hash_password(password);
        assert!(verify_password(password, &new_hash));
    }
}
